.PHONY: run initial_setup

include  ../hangar.mk

TARGET_FILES=$(BLD_BMV2)/networks/p4_tutorials/monitor/monitor.json

run:
    HANGARGAMES=/home/vagrant/Hangar/ TOPOLOGY=/home/vagrant/Hangar/networks/p4_tutorials/monitor/topology.yml ./run_monitor.sh

initial_setup:
	echo "initial_setup"


